@startuml
Note as Note1
    Different type of node(Building, Hotel, School etc) on a Map
    We need to export these class objects to an XML or PDF
end note
note top of Client : Building b = new Building();\n IExportVisitor visitor = new XMLExportVisitor()\n b.export(visitor)
class Client #violet
Client o-d-> Building
Client o-d-> Hotel
Client o-d-> IExportVisitor
interface IMapNode{
    + export(visitor: IExportVisitor)
}
IMapNode o-> IExportVisitor
XMLExportVisitor o-l-> Building
XMLExportVisitor o-l-> Hotel
PDFExportVisitor o-l-> Building
PDFExportVisitor o-l-> Hotel
note bottom of Building :export(IExportVisitor){\n visitor.export(this) \n}
class Building implements IMapNode{
    ...
    + export(IExportVisitor)
}
class Hotel implements IMapNode{
    ...
    + export(IExportVisitor)
}
interface IExportVisitor{
    + export(Building)
    + export(Hotel)
}
class XMLExportVisitor implements IExportVisitor{
    + export(Building)
    + export(Hotel)
}
class PDFExportVisitor implements IExportVisitor{
    + export(Building)
    + export(Hotel)
}
@enduml