@startuml
class Client #violet
note top of Context: Context is the sentence of the language,\n which will be interpreted
class Context
Client o-> Context
Client o-down-> IExpression
interface IExpression{
    +interpret(Context)
}
class TerminalExpression implements IExpression{
    +interpret(Context)
}
class CompositeExpression implements IExpression{
    - expressions : List<IExpression>
    +interpret(Context)
}
CompositeExpression o--> IExpression
@enduml