#*.puml can be used with Intellij PlantUML Plugin to generate the UML diagrams

@startuml
note top of Client: IValidationHandler handler = new ConcreteHandler1();\n handler.setNext(new ConcreteHandler2())\n handler.validate()\n //Client can decide order
class Client #violet
note top of Context: Context is the sentence of the language,\n which will be interpreted
class Context
Client o-> Context
Client o-down-> IExpression
interface IExpression{
    +interpret(Context)
}
class TerminalExpression implements IExpression{
    +interpret(Context)
}
class CompositeExpression implements IExpression{
    - expressions : List<IExpression>
    +interpret(Context)
}
CompositeExpression o--> IExpression
@enduml