@startuml
class Client #violet
class IComponent <<interface>>
note top of Client : IComponent component = new CompositeComponent()\n component.execute()
Client -right-> IComponent
interface IComponent{
    + execute()
}
class LeafComponent implements IComponent{
    + execute()
}
note top of CompositeComponent : Delegates task to list of components\n execute()=IComponent1.execute()+IComponent1.execute()+...\n Note - Here done using iteration
class CompositeComponent implements IComponent{
    - components: List<IComponent>
    + addComponent()
    + removeComponent()
    + execute()
}
CompositeComponent o-up-> IComponent
@enduml