@startuml
note as Note1
    UML is around Build-House example
    Note if one of Step is private method to be invoked by Parent Step(i.e.buildHouse())

    public final void buildHouse(){\n
        buildFoundation();\n
        buildPillars();\n
        buildWalls();\n
        buildWindows();\n
        System.out.println("House is built.");\n
    }
end note
class Client #violet
Client o-> IBuildHouse
interface IBuildHouse{
    + default final buildHouse()
    + abstract buildWalls()
    + abstract buildPillars()
    + default buildWindows()
}
class AbstractBuildHouse implements IBuildHouse{
    - private field
    + equals()
    + hashcode()
}
class WoodenHouse extends AbstractBuildHouse{
    + buildWalls()
    + buildPillars()
}
class ClassHouse extends AbstractBuildHouse{
    + buildWalls()
    + buildPillars()
    + buildWindows()
}
@enduml