@startuml
note as Note1
    UML is around Build-House example
    }
end note
note top of Client : IBuildHouse buildHouse = new WoodenHouse();\nbuildHouse.buildHouse()
class Client #violet
Client o-> IBuildHouse
interface IBuildHouse{
    + buildHouse()
    + abstract buildWalls()
    + abstract buildPillars()
    + default buildWindows()
}
note top of AbstractBuildHouse: public final void buildHouse(){\n buildFoundation();\n buildPillars();\n buildWalls();\n buildWindows();\n System.out.println("House is built.");\n
class AbstractBuildHouse implements IBuildHouse{
    + public final buildHouse()
    + abstract buildWalls()
    + abstract buildPillars()
    - private field
    + equals()
    + hashcode()
}
class WoodenHouse extends AbstractBuildHouse{
    + buildWalls()
    + buildPillars()
}
class ClassHouse extends AbstractBuildHouse{
    + buildWalls()
    + buildPillars()
    + buildWindows()
}
@enduml
