#*.puml can be used with Intellij PlantUML Plugin to generate the UML diagrams

@startuml
class Client #violet
class IPizza <<interface>>
BasePizzaDecorator o-up-> IPizza
note top of Client : IPizza pizza = new PizzaDecoratorTopping2(new PizzaDecoratorTopping1(new BasePizza())\n pizza.price()\nCall Stack: PizzaDecoratorTopping2.price() -> PizzaDecoratorTopping1.price() -> BasePizzaDecorator.price()\n Execution: BasePizzaDecorator.price() -> PizzaDecoratorTopping1.price() -> PizzaDecoratorTopping2.price()
Client -right-> IPizza : uses
interface IPizza{
    + price()
}
class BasePizza implements IPizza{
    + price()
}
note top of BasePizzaDecorator : price()=pizza.price()
class BasePizzaDecorator implements IPizza{
    - IPizza
    + BasePizzaDecorator(pizza : IPizza)
    + price()
}
note top of PizzaDecoratorTopping1 : PizzaDecoratorTopping1(pizza : IPizza) = super(pizza)\n price()=super.price()+10$
class PizzaDecoratorTopping1 implements BasePizzaDecorator{
    + PizzaDecoratorTopping1(pizza : IPizza)
    + price()
}
note top of PizzaDecoratorTopping2 : PizzaDecoratorTopping2(pizza : IPizza) = super(pizza)\n price()=super.price()+20$
class PizzaDecoratorTopping2 implements BasePizzaDecorator{
    + PizzaDecoratorTopping2(pizza : IPizza)
    + price()
}
@enduml