#*.puml can be used with Intellij PlantUML Plugin to generate the UML diagrams

@startuml
class Client #violet
package com.memento{
    class Originator{
        - state
        + saveMemento(): Memento
        + restoreMemento(memento: Memento)
    }

    note top of OriginatorMemento : Notice private methods
    class OriginatorMemento{
        - state
        - getState()
    }
}
Client o-> MementoCareTaker
Originator o-> OriginatorMemento
MementoCareTaker o-> Originator
note top of MementoCareTaker : undo(){\n m = memento[](size);\noriginator.restoreMemento(m) \n}
class MementoCareTaker{
    - originator: Originator
    - memento[] : Memento
    + undo()
}
@enduml